### ISSUE TITLE
To do List

### ISSUE THREAD

**Issue by Xaethon** [Xaethon/Genesis#1]
- Reassign Sprint Key
- Reassign Invtweaks Key?
- Update Forbidden Magic

**Comment by Ryathael** [comment]
Gonna toss a few suggested "config" changes here for you, as I have time and play through it in Singleplayer.

1.) Add a "recipe" so that we can somehow get Silicon through TE machines too. (and possibly Mek one also.)   (I would suggest sand in the pulverizer and whatever the equivalent Mek machine is, provided they dont give a secondary item)

**Comment by buglord** [comment]
enrich sand for silicon? no other recipe for enriching sand is there? would make enough sense.
